name = "video-downloader-bot"
main = "src/index.ts"
compatibility_date = "2024-04-18"

[vars]
# As chaves a seguir devem ser setadas via CLI "wrangler secret put <NOME>"
# TELEGRAM_BOT_TOKEN
# RAPIDAPI_KEY
# RAPIDAPI_HOST

[[d1_databases]]
binding = "DB"
database_name = "video-downloader-db"
database_id = "COLOQUE_SEU_D1_ID_AQUI"
